<?php

namespace Pasantias\EmpresasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostulacionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostulacionesRepository extends EntityRepository
{
}
