parameters:
#    pasantias.example.class: Pasantias\PasantiasBundle\Example

services:
#    pasantias.example:
#        class: %pasantias.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
