security:
    encoders:
        Pasantias\UsuariosBundle\Entity\Usuarios:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10
        Symfony\Component\Security\Core\User\User: plaintext
 
    role_hierarchy:
#        ROLE_ADMIN: ROLE_USER
#        ROLE_USER: [ROLE_EMPRESA, ROLE_ALUMNO, ROLE_PROFESOR]
#        ROLE_ADMIN: [ROLE_EMPRESA, ROLE_ALUMNO, ROLE_PROFESOR]
    providers:
        chain_provider:
            chain:
                providers: [in_memory, usuarios]
        in_memory:
            memory:
                users:
                    admin: { password: 123456, roles: ROLE_ADMIN }
        usuarios:
            entity: { class: Pasantias\UsuariosBundle\Entity\Usuarios, property: usuario }
 
    firewalls:
        main:
#            pattern: /.*
            pattern: ^/*
            provider: chain_provider
            form_login:
                login_path: login
                check_path: login_check
                remember_me: true
                always_use_default_target_path: true
            logout:
                path: logout
                target: login
                invalidate_session: false
            remember_me:
                key: MiClaveSegura
                lifetime: 1800
                path: /.*
                domain: ~
#            security: true
            anonymous: ~
    access_control:
        - { path: ^/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/registrar, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: /user, roles: ROLE_USER }
#        - { path: /admin, roles: ROLE_ADMIN }
#        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [ROLE_ALUMNO,ROLE_EMPRESA,ROLE_PROFESOR,ROLE_ADMIN] }