<?php

namespace Pasantias\CurriculumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FormacionAcademicaSecundariaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormacionAcademicaSecundariaRepository extends EntityRepository
{
}
