<?php

namespace Pasantias\CurriculumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfesorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfesorRepository extends EntityRepository
{
}
