parameters:
#    util.example.class: Pasantias\UtilBundle\Example

services:
#    util.example:
#        class: %util.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    pasantias.twig_extension:
        class: Pasantias\UtilBundle\Twig\TwigExtension
        tags:
            - { name: twig.extension }