parameters:
#    usuarios.example.class: Pasantias\UsuariosBundle\Example

services:
#    usuarios.example:
#        class: %usuarios.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
